[project]
name = "rag-end-to-end"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "chromadb>=1.5.9",
    "deepeval>=4.1.7",
    "ipykernel>=7.3.0",
    "langchain>=1.3.14",
    "langchain-chroma>=1.1.0",
    "langchain-core>=1.5.3",
    "langchain-openai>=1.4.3",
    "langchain-text-splitters>=1.1.2",
    "openai>=2.53.0",
    "portalocker>=4.1.0",
    "pytest>=9.1.1",
    "python-dotenv>=1.2.2",
    "sentence-transformers>=5.7.0",
]
